import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
// import WinterCheckout from "winter-marketplace-checkout";
import React, { useEffect, useState } from "react";
import WinterCheckout from "winter-marketplace-checkout/lib/WinterCheckout";
// import WinterCheckout from "winter-marketplace-checkout/lib/WinterCheckout";

export default function Home() {
  const [showWinterModal, setShowWinterModal] = useState(false);

  return (
    <div className={styles.container}>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <button onClick={() => setShowWinterModal(true)}>Open winter</button>
      <WinterCheckout
        showModal={showWinterModal}
        contractAddress={"0x708E73c7A0D81e00e848c902217d2d39e56d65AF"}
        tokenId={"5593"}
        production={true}
        orderSource={"x2y2.io"}
        fillSource={"x2y2.io"}
        walletAddress={"ox3123123123"}
        email={"evankfisher"}
        onClose={() => {
          setShowWinterModal(false);
        }}
      />

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

// const WinterCheckout: React.FC<{
//   showModal: boolean;
//   contractAddress?: string;
//   tokenId?: string;
//   walletAddress?: string;
//   email?: string;
//   mintQuantity?: number;
//   production?: boolean;
//   fillSource?: string;
//   orderSource?: string;
//   onClose?: () => void;
//   onSuccess?: (txId: string, email: string) => void;
// }> = ({
//   showModal,
//   contractAddress,
//   tokenId,
//   walletAddress,
//   email,
//   mintQuantity,
//   production,
//   fillSource,
//   orderSource,
//   onClose,
//   onSuccess,
// }) => {
//   const [projectUrl, setProjectUrl] = useState("");

//   useEffect(() => {
//     if (typeof window !== "undefined") {
//       const handleWindowEvent = (
//         e: Event & {
//           data:
//             | { name: string; transactionhash: string; email: string }
//             | string;
//         }
//       ) => {
//         if (typeof e.data === "string") {
//           if (e.data === "closeWinterCheckoutModal") {
//             onClose?.();
//           }
//         } else {
//           if (e.data.name === "closeWinterCheckoutModal") {
//             onClose?.();
//           }
//         }
//       };
//       window.addEventListener("message", handleWindowEvent);
//       return () => window.removeEventListener("message", handleWindowEvent);
//     }
//   }, [onClose, onSuccess]);

//   useEffect(() => {
//     let queryString = "contractAddress=" + contractAddress;
//     queryString += "&tokenId=" + tokenId;
//     if (walletAddress) {
//       queryString += "&walletAddress=" + walletAddress;
//     }
//     if (email) {
//       queryString += "&email=" + email;
//     }
//     if (mintQuantity) {
//       queryString += "&mintQuantity=" + mintQuantity;
//     }
//     if (fillSource) {
//       queryString += `&fillSource=` + fillSource;
//     }
//     if (orderSource) {
//       queryString += `&orderSource=` + orderSource;
//     }

//     const url = production
//       ? "https://production-marketplace-nft-checkout.onrender.com/?" +
//         queryString
//       : "https://sandbox-marketplace-nft-checkout.onrender.com/?" + queryString;

//     setProjectUrl(url);
//   }, [
//     contractAddress,
//     tokenId,
//     production,
//     walletAddress,
//     email,
//     mintQuantity,
//     orderSource,
//     fillSource,
//   ]);

//   return showModal ? (
//     <div
//       dangerouslySetInnerHTML={{
//         __html: `<iframe id="winter-checkout" src="${projectUrl}" style="color-scheme: light; position: fixed; top: 0px; bottom: 0px; right: 0px; width: 100%; border: none; margin: 0px; padding: 0px; overflow: hidden; z-index: 999999; height: 100%;" />`,
//       }}
//     />
//   ) : (
//     <></>
//   );
// };
